name: Financials Deployment
on:
  push:
    branches:
      - master
    path:
      - financials-deployment.yaml
jobs:
  financials_deployment:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout deployment code
        uses: actions/checkout@v2
