name: Financials Deployment
on:
  push:
    branches:
      - master
    paths:
      - financials-deployment.yaml
jobs:
  financials_deployment:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout deployment code
        uses: actions/checkout@v2
      - name: Install yq
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y
          yq --version
      - name: display
        run: |
          array=$(yq r financials-deployment.yaml *.deployTo | sed -e "s/- //")
          deployTo=($array)
          array=$(yq r ffinancials-deployment.yaml *.copyAllReleases | sed -e "s/- //")
          copyAllReleases=($array)
          array=$(yq r financials-deployment.yaml *.excludeDeploy | sed -e "s/- //")
          excludeDeploy=($array)
          echo $deployTo $copyAllReleases $excludeDeploy
          
          
          
